"""Agent 3 — UI Component Designer.

    lookup_tailwind      REAL. A maintained reference of Tailwind utility
                         families *plus* this project's own theme tokens, read
                         out of `frontend/tailwind.config.ts` at first use — so
                         the agent knows `bg-surface` and `rounded-ctl` exist
                         here, which no generic Tailwind cheat sheet would.
                         Also validates: it reports whether each class the
                         agent asked about is real.
    lookup_lucide_icons  REAL. Searches the icon names generated from the exact
                         `lucide-react` build installed in frontend/, via
                         `scripts/generate_lucide_icons.py`. An icon outside
                         that list does not exist in this project and would
                         render as nothing.

The component "mock engine" from the brief is *not* here: the markup is
generated by the model. That is recorded as a reasoning tool in the registry.
"""

from __future__ import annotations

import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

from app.agents.tools.base import ToolContext, ToolResult, as_json

log = logging.getLogger(__name__)

_DATA = Path(__file__).resolve().parents[1] / "data"
_TAILWIND_CONFIG = (
    Path(__file__).resolve().parents[4] / "frontend" / "tailwind.config.ts"
)


# ---------------------------------------------------------------------------
# Tailwind reference
# ---------------------------------------------------------------------------

# The generic half: utility families with their real value scales. This is a
# reference, not an exhaustive dump of Tailwind — the point is to keep the
# model on classes that exist and to remind it of the responsive/state prefix
# grammar, which is where generated markup usually goes wrong.
TAILWIND_REFERENCE: dict[str, dict[str, Any]] = {
    "layout": {
        "display": ["block", "inline-block", "inline", "flex", "inline-flex", "grid", "inline-grid", "hidden"],
        "position": ["static", "relative", "absolute", "fixed", "sticky"],
        "inset": ["inset-0", "inset-x-0", "inset-y-0", "top-0", "right-0", "bottom-0", "left-0"],
        "overflow": ["overflow-auto", "overflow-hidden", "overflow-x-auto", "overflow-y-auto", "overflow-clip"],
        "z": ["z-0", "z-10", "z-20", "z-30", "z-40", "z-50"],
    },
    "flex_grid": {
        "direction": ["flex-row", "flex-col", "flex-row-reverse", "flex-col-reverse"],
        "wrap": ["flex-wrap", "flex-nowrap"],
        "grow_shrink": ["flex-1", "flex-auto", "flex-none", "grow", "grow-0", "shrink", "shrink-0"],
        "justify": ["justify-start", "justify-center", "justify-end", "justify-between", "justify-around", "justify-evenly"],
        "align": ["items-start", "items-center", "items-end", "items-baseline", "items-stretch"],
        "self": ["self-start", "self-center", "self-end", "self-stretch"],
        "grid": ["grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4", "grid-cols-6", "grid-cols-12", "col-span-2", "col-span-3", "col-span-full"],
        "gap": ["gap-0", "gap-1", "gap-2", "gap-3", "gap-4", "gap-6", "gap-8", "gap-x-4", "gap-y-2"],
    },
    "spacing": {
        "scale": "0 0.5 1 1.5 2 2.5 3 3.5 4 5 6 7 8 9 10 11 12 14 16 20 24 28 32 36 40 44 48 52 56 60 64 72 80 96",
        "padding": ["p-4", "px-4", "py-2", "pt-3", "pr-2", "pb-3", "pl-2"],
        "margin": ["m-4", "mx-auto", "my-2", "mt-3", "-mt-2", "space-y-3", "space-x-2"],
        "note": "One spacing unit is 0.25rem (4px). `mx-auto` centres a block with a width.",
    },
    "sizing": {
        "width": ["w-full", "w-auto", "w-fit", "w-screen", "w-1/2", "w-1/3", "w-64", "max-w-md", "max-w-2xl", "min-w-0"],
        "height": ["h-full", "h-auto", "h-screen", "h-dvh", "h-10", "min-h-0", "max-h-96"],
        "note": "`min-w-0` on a flex child is what lets `truncate` work inside it.",
    },
    "typography": {
        "size": ["text-xs", "text-sm", "text-base", "text-lg", "text-xl", "text-2xl", "text-3xl", "text-4xl"],
        "weight": ["font-light", "font-normal", "font-medium", "font-semibold", "font-bold"],
        "family": ["font-sans", "font-serif", "font-mono"],
        "align": ["text-left", "text-center", "text-right"],
        "leading": ["leading-none", "leading-tight", "leading-snug", "leading-normal", "leading-relaxed", "leading-loose"],
        "tracking": ["tracking-tighter", "tracking-tight", "tracking-normal", "tracking-wide", "tracking-widest"],
        "other": ["truncate", "line-clamp-2", "line-clamp-3", "uppercase", "capitalize", "whitespace-nowrap", "break-words"],
    },
    "colour": {
        "note": (
            "Generic Tailwind palettes (slate/gray/zinc/red/…/50-950) exist, but "
            "prefer this project's semantic tokens under `project_tokens` below "
            "— they follow the active section's accent and the dark theme."
        ),
        "text": ["text-white", "text-black", "text-slate-500", "text-red-500"],
        "background": ["bg-white", "bg-transparent", "bg-slate-900", "bg-black/50"],
        "opacity_syntax": "Any colour takes a slash opacity: `bg-black/50`, `text-white/70`.",
    },
    "border_radius": {
        "radius": ["rounded-none", "rounded-sm", "rounded", "rounded-md", "rounded-lg", "rounded-xl", "rounded-2xl", "rounded-full"],
        "border": ["border", "border-0", "border-2", "border-t", "border-b", "border-x"],
        "ring": ["ring-1", "ring-2", "ring-offset-2", "ring-inset"],
    },
    "effects": {
        "shadow": ["shadow-sm", "shadow", "shadow-md", "shadow-lg", "shadow-xl", "shadow-none"],
        "opacity": ["opacity-0", "opacity-50", "opacity-75", "opacity-100"],
        "blur": ["blur-sm", "blur", "backdrop-blur-sm", "backdrop-blur-md", "backdrop-blur-xl"],
    },
    "interactivity": {
        "cursor": ["cursor-pointer", "cursor-not-allowed", "cursor-default"],
        "select": ["select-none", "select-text"],
        "pointer": ["pointer-events-none", "pointer-events-auto"],
        "transition": ["transition", "transition-colors", "transition-transform", "duration-150", "duration-200", "ease-out"],
    },
    "prefixes": {
        "responsive": ["sm: (≥640px)", "md: (≥768px)", "lg: (≥1024px)", "xl: (≥1280px)", "2xl: (≥1536px)"],
        "state": ["hover:", "focus:", "focus-visible:", "focus-within:", "active:", "disabled:", "group-hover:", "peer-checked:"],
        "theme": ["dark:", "motion-safe:", "motion-reduce:", "print:"],
        "rule": (
            "Mobile-first: an unprefixed class applies at every width and each "
            "breakpoint prefix applies from that width UP. Write the small "
            "layout unprefixed, then add `sm:`/`md:` — never the reverse."
        ),
    },
    "accessibility": {
        "classes": ["sr-only", "not-sr-only", "focus-visible:outline-none", "focus-visible:ring-2"],
        "rule": (
            "`sr-only` hides visually while keeping the text for screen "
            "readers — it is the right way to label an icon-only button. "
            "Never remove a focus ring without replacing it with a visible one."
        ),
    },
}


@lru_cache(maxsize=1)
def _project_tokens() -> dict[str, Any]:
    """This project's own theme tokens, read from its tailwind config.

    Parsed rather than restated, so a token renamed in the config does not
    leave the agent recommending a class that no longer resolves. It is a
    tolerant regex scrape of a TypeScript object, not a parse — if the file
    moves or changes shape, the tool reports that it could not read it instead
    of returning a stale list.
    """
    if not _TAILWIND_CONFIG.exists():
        return {"available": False, "reason": f"{_TAILWIND_CONFIG.name} not found."}

    try:
        source = _TAILWIND_CONFIG.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return {"available": False, "reason": str(exc)}

    def _keys(block_name: str) -> list[str]:
        match = re.search(rf"{block_name}:\s*\{{", source)
        if not match:
            return []
        # Walk the braces so a nested object (`ink: {{ … }}`) is consumed whole
        # rather than terminating the block at its first `}`.
        depth, start = 0, match.end() - 1
        for i in range(start, len(source)):
            if source[i] == "{":
                depth += 1
            elif source[i] == "}":
                depth -= 1
                if depth == 0:
                    body = source[start + 1 : i]
                    break
        else:
            return []
        out: list[str] = []
        depth = 0
        for line in body.splitlines():
            stripped = line.strip()
            if depth == 0:
                key = re.match(r'^["\']?([\w-]+)["\']?\s*:', stripped)
                if key and key.group(1) != "DEFAULT":
                    out.append(key.group(1))
            depth += stripped.count("{") - stripped.count("}")
        return out

    colours = _keys("colors")
    return {
        "available": True,
        "source": "frontend/tailwind.config.ts",
        "colours": colours,
        "usage": {
            "background": [f"bg-{c}" for c in colours[:14]],
            "text": ["text-ink", "text-ink-muted", "text-ink-faint", "text-accent", "text-warn", "text-del", "text-add"],
            "border": ["border-line", "border-line-strong", "border-accent-line"],
        },
        "radius": [f"rounded-{r}" for r in _keys("borderRadius")],
        "font_size": [f"text-{s}" for s in _keys("fontSize")],
        "shadow": [f"shadow-{s}" for s in _keys("boxShadow")],
        "animation": [f"animate-{a}" for a in _keys("animation")],
        "note": (
            "These are THIS project's tokens and follow the active section's "
            "accent automatically. Prefer them over raw palette classes when "
            "the component is meant to live inside this app. `accent` resolves "
            "from a CSS variable set by `data-section`, so the same markup "
            "takes on the right colour in Chat, Learn, Code or Agents."
        ),
    }


#: Enough of Tailwind's grammar to tell a real class from a plausible one
#: without shipping the framework's full class list. Anything matching here is
#: reported "plausible"; anything in the reference above is reported "known".
_CLASS_SHAPE = re.compile(
    r"^(?:(?:sm|md|lg|xl|2xl|hover|focus|focus-visible|focus-within|active|"
    r"disabled|group-hover|group-focus|peer-checked|dark|motion-safe|"
    r"motion-reduce|first|last|odd|even|print):)*"
    r"-?[a-z][a-z0-9]*(?:-[a-z0-9.]+)*(?:\/\d{1,3})?(?:\[[^\]]+\])?$"
)


def _flatten_reference() -> set[str]:
    out: set[str] = set()
    for group in TAILWIND_REFERENCE.values():
        for value in group.values():
            if isinstance(value, list):
                out.update(v.split(" ")[0] for v in value)
    tokens = _project_tokens()
    if tokens.get("available"):
        for key in ("radius", "font_size", "shadow", "animation", "border", "text", "background"):
            value = tokens.get(key) or (tokens.get("usage") or {}).get(key)
            if isinstance(value, list):
                out.update(value)
    return out


async def lookup_tailwind(ctx: ToolContext, args: dict) -> ToolResult:
    """Look up utility families, and validate specific classes."""
    query = (args.get("query") or "").strip().lower()
    classes = args.get("classes") or []
    if isinstance(classes, str):
        classes = classes.split()

    payload: dict[str, Any] = {}

    if classes:
        known = _flatten_reference()
        checked = []
        for raw in classes[:60]:
            name = str(raw).strip()
            if not name:
                continue
            base = name.split(":")[-1]
            if name in known or base in known:
                verdict = "known"
            elif _CLASS_SHAPE.match(name):
                verdict = "plausible"
            else:
                verdict = "malformed"
            checked.append({"class": name, "verdict": verdict})
        payload["validated"] = checked
        payload["validation_note"] = (
            "`known` is in this reference. `plausible` is well-formed Tailwind "
            "grammar that this reference does not enumerate — most of the "
            "spacing and colour scales fall here, and they are usually fine. "
            "`malformed` cannot be a Tailwind class at all; replace it."
        )

    if query:
        matches = {
            group: {
                key: value
                for key, value in entries.items()
                if query in key.lower()
                or (isinstance(value, list) and any(query in v.lower() for v in value))
                or (isinstance(value, str) and query in value.lower())
            }
            for group, entries in TAILWIND_REFERENCE.items()
        }
        payload["reference"] = {g: e for g, e in matches.items() if e} or {
            "note": f"Nothing matched `{query}`. Omit `query` to see every family."
        }
    elif not classes:
        payload["reference"] = TAILWIND_REFERENCE

    payload["project_tokens"] = _project_tokens()
    return ToolResult(output=as_json(payload, limit=16_000), meta={"query": query})


# ---------------------------------------------------------------------------
# Lucide icons
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def _icons() -> dict[str, Any]:
    path = _DATA / "lucide_icons.json"
    if not path.exists():
        return {"version": "unknown", "icons": []}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        log.warning("Could not read the Lucide icon list", exc_info=True)
        return {"version": "unknown", "icons": []}


def icon_exists(name: str) -> bool:
    return name in set(_icons().get("icons") or [])


#: Concepts to icon names. Lucide's names are literal ("Trash2", "GitBranch"),
#: so a search for "delete" or "version control" finds nothing without this.
#: Only the mappings that a substring search genuinely misses are listed.
_SYNONYMS: dict[str, tuple[str, ...]] = {
    "delete": ("Trash2", "Trash", "X", "CircleX", "Eraser"),
    "remove": ("Minus", "X", "Trash2"),
    "add": ("Plus", "CirclePlus", "SquarePlus"),
    "edit": ("Pencil", "SquarePen", "PenLine"),
    "save": ("Save", "HardDrive", "Download"),
    "loading": ("LoaderCircle", "Loader", "RefreshCw"),
    "success": ("Check", "CircleCheck", "BadgeCheck"),
    "error": ("CircleAlert", "TriangleAlert", "OctagonX"),
    "warning": ("TriangleAlert", "CircleAlert"),
    "info": ("Info", "CircleHelp"),
    "menu": ("Menu", "EllipsisVertical", "Ellipsis"),
    "close": ("X", "CircleX"),
    "back": ("ArrowLeft", "ChevronLeft"),
    "forward": ("ArrowRight", "ChevronRight"),
    "expand": ("ChevronDown", "Maximize2", "Expand"),
    "collapse": ("ChevronUp", "Minimize2"),
    "settings": ("Settings", "Settings2", "SlidersHorizontal", "Cog"),
    "profile": ("User", "CircleUser", "UserRound"),
    "logout": ("LogOut", "DoorOpen"),
    "search": ("Search", "Telescope"),
    "filter": ("Filter", "SlidersHorizontal", "ListFilter"),
    "sort": ("ArrowUpDown", "ArrowDownWideNarrow"),
    "upload": ("Upload", "CloudUpload", "FileUp"),
    "download": ("Download", "CloudDownload", "FileDown"),
    "notification": ("Bell", "BellRing", "BellDot"),
    "favourite": ("Star", "Heart", "Bookmark"),
    "favorite": ("Star", "Heart", "Bookmark"),
    "security": ("Shield", "ShieldCheck", "Lock", "KeyRound"),
    "version control": ("GitBranch", "GitCommitHorizontal", "GitPullRequest", "Github"),
    "database": ("Database", "Server", "HardDrive", "Table2"),
    "analytics": ("ChartLine", "ChartColumn", "ChartPie", "TrendingUp"),
    "chart": ("ChartLine", "ChartColumn", "ChartPie", "ChartArea"),
    "money": ("DollarSign", "CreditCard", "Wallet", "Banknote", "Receipt"),
    "time": ("Clock", "Timer", "CalendarDays", "Hourglass"),
    "email": ("Mail", "Send", "Inbox", "AtSign"),
    "chat": ("MessageSquare", "MessageCircle", "MessagesSquare"),
    "ai": ("Sparkles", "Bot", "BrainCircuit", "Wand2"),
    "code": ("Code", "CodeXml", "Terminal", "Braces", "FileCode"),
    "dark mode": ("Moon", "MoonStar"),
    "light mode": ("Sun", "SunMedium"),
}


async def lookup_lucide_icons(ctx: ToolContext, args: dict) -> ToolResult:
    """Find valid icon names for a concept, or validate the ones you picked."""
    data = _icons()
    all_icons: list[str] = list(data.get("icons") or [])
    if not all_icons:
        return ToolResult(
            "The Lucide icon list has not been generated. Run "
            "`python scripts/generate_lucide_icons.py` in backend/. Do not "
            "guess icon names in the meantime — say you could not verify them.",
            success=False,
        )

    lookup = set(all_icons)
    query = (args.get("query") or "").strip()
    names = args.get("names") or []
    if isinstance(names, str):
        names = names.split()

    payload: dict[str, Any] = {"lucide_version": data.get("version")}

    if names:
        payload["validated"] = [
            {"name": str(n), "exists": str(n) in lookup} for n in names[:40]
        ]
        missing = [v["name"] for v in payload["validated"] if not v["exists"]]
        if missing:
            payload["replace"] = {
                name: _suggest(name, all_icons, lookup)[:5] for name in missing
            }

    if query:
        payload["matches"] = _suggest(query, all_icons, lookup)[:30]
        if not payload["matches"]:
            payload["matches_note"] = (
                f"Nothing matched `{query}`. Lucide names are literal — try the "
                "object rather than the action ('Trash2' not 'delete')."
            )

    if not names and not query:
        payload["total"] = len(all_icons)
        payload["note"] = "Pass `query` to search or `names` to validate."

    return ToolResult(output=as_json(payload), meta={"count": len(all_icons)})


def _suggest(term: str, all_icons: list[str], lookup: set[str]) -> list[str]:
    term = term.strip()
    lowered = term.lower()
    out: list[str] = []

    for concept, icons in _SYNONYMS.items():
        if lowered in concept or concept in lowered:
            out.extend(i for i in icons if i in lookup)

    # Substring on the CamelCase name, then on its words, so "arrow up" finds
    # ArrowUp even though the name has no space in it.
    squashed = re.sub(r"[^a-z0-9]", "", lowered)
    for name in all_icons:
        flat = name.lower()
        if lowered and (lowered in flat or (squashed and squashed in flat)):
            out.append(name)

    seen: set[str] = set()
    return [i for i in out if not (i in seen or seen.add(i))]


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

SCHEMAS: dict[str, dict] = {
    "lookup_tailwind": {
        "name": "lookup_tailwind",
        "description": (
            "Look up Tailwind utility families, and validate specific classes. "
            "Pass `query` to browse a family ('flex', 'shadow', 'responsive'), "
            "`classes` to check ones you intend to write, or both. The result "
            "also includes THIS project's own theme tokens, read from its "
            "tailwind.config.ts — prefer those when the component is meant to "
            "live inside this app, because they follow the section accent."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "A utility family or concept to look up.",
                },
                "classes": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Classes to validate before you write them.",
                },
            },
            "required": [],
        },
    },
    "lookup_lucide_icons": {
        "name": "lookup_lucide_icons",
        "description": (
            "Search or validate Lucide icon names against the exact "
            "`lucide-react` build installed in this project. Call it before "
            "naming ANY icon: an icon outside this list does not exist here and "
            "renders as nothing. Pass `query` to find icons for a concept, or "
            "`names` to check the ones you picked."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "What the icon should depict, e.g. 'delete', 'chart'.",
                },
                "names": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Icon names to validate, e.g. ['Trash2', 'Send'].",
                },
            },
            "required": [],
        },
    },
}

HANDLERS = {
    "lookup_tailwind": lookup_tailwind,
    "lookup_lucide_icons": lookup_lucide_icons,
}
